  - name: Install packages
    ansible.builtin.apt:
      name:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
      state: latest
      update_cache: true

  - name: Add GPG Key
    ansible.builtin.apt_key:
      url: "https://download.docker.com/linux/debian/gpg"
      state: present

  - name: Set Up Repository
    ansible.builtin.apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable"
      state: present
      filename: docker
    
  - name: Install Docker
    ansible.builtin.apt:
      name:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        - docker-compose-plugin
      state: present
      update_cache: true

  - name: Add user to group Docker
    user:
      name: '{{ user }}'
      groups: docker
      append: yes


      
        
      

